---
- hosts: sanjay
  user: ansible
  become: yes
  tasks:
    - name: Install docker and some dependencies
      yum:
        name: python3-pip
        state: present


    - name: Install docker python module
      pip:
        name: docker
    - name: Create Mysql container
      docker_container:
        name: mysql
        image: mysql
        state: started
        recreate: yes
        command: sleep infinity
