---
- hosts: sanjay
  user: ansible
  become: yes
  vars:
   - package: git
  tasks:
   - name: install java latest
     yum:
       name: java
       state: latest
   - name: install docker latest
     yum:
       name: docker
       state: latest
   - name: start
     service:
       name: docker
       state: started
   - name: install git
     yum:
       name: "{{ package }}"
       state: latest
   
