apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    env: pro  
spec:
  containers:
  - name: myapp
    image: sonatype/nexus3
    resources:
      limits:
        memory: "100Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
