apiVersion: v1
kind: Pod
  name: myapp
  labels: app
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8081:32078
